#%RAML 1.0
title: swiggy-orders-sapi
baseUri: http://localhost:8081
mediaType: 
- application/json

types:
  Order: !include datatypes/Order.raml
  OrderRequest: !include datatypes/OrderRequest.raml
  OrderItem: !include datatypes/OrderItem.raml
  OrderItemRequest: !include datatypes/OrderItemRequest.raml
resourceTypes:
  collection: !include resourceTypes/collection.raml 
  member: !include resourceTypes/member.raml
traits:
  pageable: !include traits/Pageable.raml
  
/customers:
  /{id}:
    /orders:
      type: collection
      get:
        is:
          - pageable  

/orders:
  type: collection    
  get:
    is:
      - pageable
  post:
  
  /{orderId}:
    type: member      
    get:
    put:
    /orderItems:
      type: collection        
      get:
        is:
          - pageable
      post:
      /{id}:
        get:
        delete:
        put: