#%RAML 1.0
title: swiggy-orders-sapi
baseUri: http://localhost:8082
mediaType: 
- application/json

types:
  Order: !include dataTypes/Order.raml
  OrderItem: !include dataTypes/OrderItem.raml
  ErrorMessage: !include dataTypes/ErrorMessage.raml

/customers:
   /{id}:
    /orders:
     get:
       responses:
         200:
          body:
           type: Order[]
           
         500:
          body:
           type: ErrorMessage
           example:
             {
                "status": "500",
                "message": "There was some server side problem. please try later"
              } 
