#%RAML 1.0 DataType
properties:
  orderId: string
  customerId: integer
  restaurantId: string
  deliveryAddressId: string
  orderTotalPrice: integer
  orderStatus: string
  orderTime: string
  OrderItems:
   type: array
   items: !include OrderItem.raml
   