#%RAML 1.0 DataType
type: object
properties:  
  customerId: integer
  restaurantId: integer
  deliveryAddressId: integer
  orderTotalPrice: integer
  orderStatus: string
  orderTime: date-only
  orderItems:
    type: array
    items: !include OrderItem.raml
